steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/DanielaReinhardt/CICD2']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west3-docker.pkg.dev/de0360-sbx-data-academy-dr/docker-repo/my-app', '.']

# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west3-docker.pkg.dev/de0360-sbx-data-academy-dr/docker-repo/my-app']  
  
# start container as job using  cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - 'my-app'
  - '--image'
  - 'europe-west3-docker.pkg.dev/de0360-sbx-data-academy-dr/docker-repo/my-app'
  - '--region'
  - 'europe-west3'
  - '--execute-now'
images:
- 'europe-west3-docker.pkg.dev/de0360-sbx-data-academy-dr/docker-repo/my-app'
